[package]
name = "dfplot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.11", features = ["derive"] }
math = { git = "https://github.com/Banyc/math.git", rev = "bc42b7c62f7d1a07cfd7f2a8402bf093eab53ad2" }
plotly = { version = "0.8.4", features = ["kaleido"] }
polars = { version = "0.35.4", features = [
    "abs",
    "describe",
    "json",
    "lazy",
    "lazy_regex",
    "log",
    "strings",
] }
